# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'osc_gui.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1802, 1514)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        MainWindow.setFont(font)
        MainWindow.setDocumentMode(False)
        MainWindow.setDockNestingEnabled(True)
        MainWindow.setDockOptions(QtWidgets.QMainWindow.AllowNestedDocks|QtWidgets.QMainWindow.AllowTabbedDocks|QtWidgets.QMainWindow.AnimatedDocks)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralWidget)
        self.gridLayout.setContentsMargins(11, 11, 11, 11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.splitter = QtWidgets.QSplitter(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter.sizePolicy().hasHeightForWidth())
        self.splitter.setSizePolicy(sizePolicy)
        self.splitter.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.splitter.setFrameShadow(QtWidgets.QFrame.Plain)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setOpaqueResize(True)
        self.splitter.setChildrenCollapsible(False)
        self.splitter.setObjectName("splitter")
        self.graphicsView_preview = QtWidgets.QGraphicsView(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.graphicsView_preview.sizePolicy().hasHeightForWidth())
        self.graphicsView_preview.setSizePolicy(sizePolicy)
        self.graphicsView_preview.setMinimumSize(QtCore.QSize(201, 50))
        self.graphicsView_preview.setMaximumSize(QtCore.QSize(16777215, 100))
        self.graphicsView_preview.setObjectName("graphicsView_preview")
        self.graphicsView_wave = PlotWidget(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.graphicsView_wave.sizePolicy().hasHeightForWidth())
        self.graphicsView_wave.setSizePolicy(sizePolicy)
        self.graphicsView_wave.setMinimumSize(QtCore.QSize(200, 200))
        self.graphicsView_wave.setResizeAnchor(QtWidgets.QGraphicsView.NoAnchor)
        self.graphicsView_wave.setObjectName("graphicsView_wave")
        self.gridLayout.addWidget(self.splitter, 0, 0, 1, 1)
        self.widget_serial_text = QtWidgets.QWidget(self.centralWidget)
        self.widget_serial_text.setMinimumSize(QtCore.QSize(0, 400))
        self.widget_serial_text.setObjectName("widget_serial_text")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.widget_serial_text)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setSpacing(6)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.splitter_4 = QtWidgets.QSplitter(self.widget_serial_text)
        self.splitter_4.setOrientation(QtCore.Qt.Vertical)
        self.splitter_4.setObjectName("splitter_4")
        self.textBrowser_3 = QtWidgets.QTextBrowser(self.splitter_4)
        self.textBrowser_3.setObjectName("textBrowser_3")
        self.plainTextEdit_3 = QtWidgets.QPlainTextEdit(self.splitter_4)
        self.plainTextEdit_3.setObjectName("plainTextEdit_3")
        self.gridLayout_6.addWidget(self.splitter_4, 0, 0, 1, 1)
        self.pushButton_13 = QtWidgets.QPushButton(self.widget_serial_text)
        self.pushButton_13.setMinimumSize(QtCore.QSize(0, 48))
        self.pushButton_13.setObjectName("pushButton_13")
        self.gridLayout_6.addWidget(self.pushButton_13, 1, 0, 1, 1)
        self.gridLayout.addWidget(self.widget_serial_text, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1802, 24))
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtWidgets.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.menuBar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuView = QtWidgets.QMenu(self.menuBar)
        self.menuView.setObjectName("menuView")
        MainWindow.setMenuBar(self.menuBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.dockWidget_control = QtWidgets.QDockWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dockWidget_control.sizePolicy().hasHeightForWidth())
        self.dockWidget_control.setSizePolicy(sizePolicy)
        self.dockWidget_control.setFloating(False)
        self.dockWidget_control.setObjectName("dockWidget_control")
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout_6.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_6.setSpacing(6)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.pushButton_ctrl_dock = QtWidgets.QPushButton(self.dockWidgetContents)
        self.pushButton_ctrl_dock.setObjectName("pushButton_ctrl_dock")
        self.verticalLayout_6.addWidget(self.pushButton_ctrl_dock)
        self.scrollArea_2 = QtWidgets.QScrollArea(self.dockWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea_2.sizePolicy().hasHeightForWidth())
        self.scrollArea_2.setSizePolicy(sizePolicy)
        self.scrollArea_2.setMinimumSize(QtCore.QSize(425, 0))
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 475, 1219))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.scrollAreaWidgetContents_2)
        self.horizontalLayout.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox_3 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_2)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_4.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_4.setSpacing(6)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_6 = QtWidgets.QLabel(self.groupBox_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_4.addWidget(self.label_6)
        self.line = QtWidgets.QFrame(self.groupBox_3)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_4.addWidget(self.line)
        self.label_5 = QtWidgets.QLabel(self.groupBox_3)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_4.addWidget(self.label_5)
        self.comboBox_couple_mode = QtWidgets.QComboBox(self.groupBox_3)
        self.comboBox_couple_mode.setObjectName("comboBox_couple_mode")
        self.comboBox_couple_mode.addItem("")
        self.comboBox_couple_mode.addItem("")
        self.verticalLayout_4.addWidget(self.comboBox_couple_mode)
        self.label_8 = QtWidgets.QLabel(self.groupBox_3)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_4.addWidget(self.label_8)
        self.comboBox_4 = QtWidgets.QComboBox(self.groupBox_3)
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.verticalLayout_4.addWidget(self.comboBox_4)
        self.label_9 = QtWidgets.QLabel(self.groupBox_3)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_4.addWidget(self.label_9)
        self.comboBox_5 = QtWidgets.QComboBox(self.groupBox_3)
        self.comboBox_5.setObjectName("comboBox_5")
        self.verticalLayout_4.addWidget(self.comboBox_5)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem)
        self.lcdNumber_ofst_ch1 = QtWidgets.QLCDNumber(self.groupBox_3)
        self.lcdNumber_ofst_ch1.setObjectName("lcdNumber_ofst_ch1")
        self.verticalLayout_4.addWidget(self.lcdNumber_ofst_ch1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.dial_ofst_ch1 = QtWidgets.QDial(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dial_ofst_ch1.sizePolicy().hasHeightForWidth())
        self.dial_ofst_ch1.setSizePolicy(sizePolicy)
        self.dial_ofst_ch1.setMinimumSize(QtCore.QSize(50, 50))
        self.dial_ofst_ch1.setMaximumSize(QtCore.QSize(50, 50))
        self.dial_ofst_ch1.setMinimum(-120)
        self.dial_ofst_ch1.setMaximum(120)
        self.dial_ofst_ch1.setObjectName("dial_ofst_ch1")
        self.horizontalLayout_2.addWidget(self.dial_ofst_ch1)
        self.toolButton_ofst_ch1 = QtWidgets.QToolButton(self.groupBox_3)
        self.toolButton_ofst_ch1.setText("")
        self.toolButton_ofst_ch1.setObjectName("toolButton_ofst_ch1")
        self.horizontalLayout_2.addWidget(self.toolButton_ofst_ch1)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.pushButton_ofst_rst_ch1 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_ofst_rst_ch1.setObjectName("pushButton_ofst_rst_ch1")
        self.verticalLayout_4.addWidget(self.pushButton_ofst_rst_ch1)
        self.lcdNumber_gain_ch1 = QtWidgets.QLCDNumber(self.groupBox_3)
        self.lcdNumber_gain_ch1.setSmallDecimalPoint(False)
        self.lcdNumber_gain_ch1.setObjectName("lcdNumber_gain_ch1")
        self.verticalLayout_4.addWidget(self.lcdNumber_gain_ch1)
        self.dial_gain_ch1 = QtWidgets.QDial(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dial_gain_ch1.sizePolicy().hasHeightForWidth())
        self.dial_gain_ch1.setSizePolicy(sizePolicy)
        self.dial_gain_ch1.setMinimumSize(QtCore.QSize(100, 100))
        self.dial_gain_ch1.setMaximumSize(QtCore.QSize(16777215, 100))
        self.dial_gain_ch1.setWrapping(False)
        self.dial_gain_ch1.setNotchesVisible(False)
        self.dial_gain_ch1.setObjectName("dial_gain_ch1")
        self.verticalLayout_4.addWidget(self.dial_gain_ch1)
        self.horizontalLayout.addWidget(self.groupBox_3)
        self.groupBox_4 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_2)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_5.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_5.setSpacing(6)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_7 = QtWidgets.QLabel(self.groupBox_4)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_5.addWidget(self.label_7)
        self.line_2 = QtWidgets.QFrame(self.groupBox_4)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_5.addWidget(self.line_2)
        self.label_10 = QtWidgets.QLabel(self.groupBox_4)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_5.addWidget(self.label_10)
        self.comboBox_6 = QtWidgets.QComboBox(self.groupBox_4)
        self.comboBox_6.setObjectName("comboBox_6")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.verticalLayout_5.addWidget(self.comboBox_6)
        self.pushButton_preview_view = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_preview_view.setCheckable(True)
        self.pushButton_preview_view.setChecked(True)
        self.pushButton_preview_view.setObjectName("pushButton_preview_view")
        self.verticalLayout_5.addWidget(self.pushButton_preview_view)
        self.pushButton_freq_domain = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_freq_domain.setCheckable(True)
        self.pushButton_freq_domain.setObjectName("pushButton_freq_domain")
        self.verticalLayout_5.addWidget(self.pushButton_freq_domain)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem1)
        self.lcdNumber_time_ofst = QtWidgets.QLCDNumber(self.groupBox_4)
        self.lcdNumber_time_ofst.setObjectName("lcdNumber_time_ofst")
        self.verticalLayout_5.addWidget(self.lcdNumber_time_ofst)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_5.setSpacing(6)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.dial_ofst_time = QtWidgets.QDial(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dial_ofst_time.sizePolicy().hasHeightForWidth())
        self.dial_ofst_time.setSizePolicy(sizePolicy)
        self.dial_ofst_time.setMinimumSize(QtCore.QSize(50, 50))
        self.dial_ofst_time.setMaximumSize(QtCore.QSize(50, 50))
        self.dial_ofst_time.setMinimum(-120)
        self.dial_ofst_time.setMaximum(120)
        self.dial_ofst_time.setObjectName("dial_ofst_time")
        self.horizontalLayout_5.addWidget(self.dial_ofst_time)
        self.toolButton_ofst_time = QtWidgets.QToolButton(self.groupBox_4)
        self.toolButton_ofst_time.setText("")
        self.toolButton_ofst_time.setObjectName("toolButton_ofst_time")
        self.horizontalLayout_5.addWidget(self.toolButton_ofst_time)
        self.verticalLayout_5.addLayout(self.horizontalLayout_5)
        self.pushButton_ofst_rst_time = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_ofst_rst_time.setObjectName("pushButton_ofst_rst_time")
        self.verticalLayout_5.addWidget(self.pushButton_ofst_rst_time)
        self.lcdNumber_time_scale = QtWidgets.QLCDNumber(self.groupBox_4)
        self.lcdNumber_time_scale.setObjectName("lcdNumber_time_scale")
        self.verticalLayout_5.addWidget(self.lcdNumber_time_scale)
        self.dial_time_scale = QtWidgets.QDial(self.groupBox_4)
        self.dial_time_scale.setMinimumSize(QtCore.QSize(100, 100))
        self.dial_time_scale.setMaximumSize(QtCore.QSize(16777215, 100))
        self.dial_time_scale.setObjectName("dial_time_scale")
        self.verticalLayout_5.addWidget(self.dial_time_scale)
        self.horizontalLayout.addWidget(self.groupBox_4)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(-1, 0, -1, 6)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.comboBox_trigger_mode = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_trigger_mode.setObjectName("comboBox_trigger_mode")
        self.comboBox_trigger_mode.addItem("")
        self.comboBox_trigger_mode.addItem("")
        self.comboBox_trigger_mode.addItem("")
        self.verticalLayout_2.addWidget(self.comboBox_trigger_mode)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.spinBox_trigger_level = QtWidgets.QSpinBox(self.groupBox)
        self.spinBox_trigger_level.setMaximum(255)
        self.spinBox_trigger_level.setProperty("value", 127)
        self.spinBox_trigger_level.setObjectName("spinBox_trigger_level")
        self.verticalLayout_2.addWidget(self.spinBox_trigger_level)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.dial_time_ofst_2 = QtWidgets.QDial(self.groupBox)
        self.dial_time_ofst_2.setMinimumSize(QtCore.QSize(50, 50))
        self.dial_time_ofst_2.setMaximumSize(QtCore.QSize(50, 50))
        self.dial_time_ofst_2.setMinimum(-120)
        self.dial_time_ofst_2.setMaximum(120)
        self.dial_time_ofst_2.setObjectName("dial_time_ofst_2")
        self.horizontalLayout_3.addWidget(self.dial_time_ofst_2)
        self.toolButton_2 = QtWidgets.QToolButton(self.groupBox)
        self.toolButton_2.setObjectName("toolButton_2")
        self.horizontalLayout_3.addWidget(self.toolButton_2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.pushButton = QtWidgets.QPushButton(self.groupBox)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_2.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout_2.addWidget(self.pushButton_2)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_6 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_2)
        self.groupBox_6.setObjectName("groupBox_6")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.groupBox_6)
        self.verticalLayout_10.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_10.setSpacing(6)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_3 = QtWidgets.QLabel(self.groupBox_6)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_10.addWidget(self.label_3)
        self.spinBox_draw_brightness = QtWidgets.QSpinBox(self.groupBox_6)
        self.spinBox_draw_brightness.setMinimum(10)
        self.spinBox_draw_brightness.setMaximum(255)
        self.spinBox_draw_brightness.setProperty("value", 200)
        self.spinBox_draw_brightness.setObjectName("spinBox_draw_brightness")
        self.verticalLayout_10.addWidget(self.spinBox_draw_brightness)
        self.label_4 = QtWidgets.QLabel(self.groupBox_6)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_10.addWidget(self.label_4)
        self.spinBox_line_width = QtWidgets.QSpinBox(self.groupBox_6)
        self.spinBox_line_width.setMinimum(1)
        self.spinBox_line_width.setMaximum(6)
        self.spinBox_line_width.setObjectName("spinBox_line_width")
        self.verticalLayout_10.addWidget(self.spinBox_line_width)
        self.label_11 = QtWidgets.QLabel(self.groupBox_6)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_10.addWidget(self.label_11)
        self.comboBox = QtWidgets.QComboBox(self.groupBox_6)
        self.comboBox.setObjectName("comboBox")
        self.verticalLayout_10.addWidget(self.comboBox)
        self.pushButton_5 = QtWidgets.QPushButton(self.groupBox_6)
        self.pushButton_5.setObjectName("pushButton_5")
        self.verticalLayout_10.addWidget(self.pushButton_5)
        self.verticalLayout.addWidget(self.groupBox_6)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.pushButton_3 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout.addWidget(self.pushButton_3)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayout_6.addWidget(self.scrollArea_2)
        self.dockWidget_control.setWidget(self.dockWidgetContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.dockWidget_control)
        self.dockWidget_measure = QtWidgets.QDockWidget(MainWindow)
        self.dockWidget_measure.setObjectName("dockWidget_measure")
        self.dockWidgetContents_4 = QtWidgets.QWidget()
        self.dockWidgetContents_4.setObjectName("dockWidgetContents_4")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.dockWidgetContents_4)
        self.verticalLayout_7.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_7.setSpacing(6)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.pushButton_meas_dock = QtWidgets.QPushButton(self.dockWidgetContents_4)
        self.pushButton_meas_dock.setObjectName("pushButton_meas_dock")
        self.verticalLayout_7.addWidget(self.pushButton_meas_dock)
        self.scrollArea = QtWidgets.QScrollArea(self.dockWidgetContents_4)
        self.scrollArea.setMinimumSize(QtCore.QSize(135, 0))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 253, 540))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_9.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_9.setSpacing(6)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.groupBox_2 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_3.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.comboBox_hor_meas_1 = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBox_hor_meas_1.setObjectName("comboBox_hor_meas_1")
        self.comboBox_hor_meas_1.addItem("")
        self.comboBox_hor_meas_1.addItem("")
        self.verticalLayout_3.addWidget(self.comboBox_hor_meas_1)
        self.lcdNumber_hor_meas_1 = QtWidgets.QLCDNumber(self.groupBox_2)
        self.lcdNumber_hor_meas_1.setObjectName("lcdNumber_hor_meas_1")
        self.verticalLayout_3.addWidget(self.lcdNumber_hor_meas_1)
        self.line_3 = QtWidgets.QFrame(self.groupBox_2)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout_3.addWidget(self.line_3)
        self.comboBox_hor_meas_2 = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBox_hor_meas_2.setObjectName("comboBox_hor_meas_2")
        self.comboBox_hor_meas_2.addItem("")
        self.comboBox_hor_meas_2.addItem("")
        self.verticalLayout_3.addWidget(self.comboBox_hor_meas_2)
        self.lcdNumber_hor_meas_2 = QtWidgets.QLCDNumber(self.groupBox_2)
        self.lcdNumber_hor_meas_2.setObjectName("lcdNumber_hor_meas_2")
        self.verticalLayout_3.addWidget(self.lcdNumber_hor_meas_2)
        self.comboBox_hor_meas_3 = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBox_hor_meas_3.setObjectName("comboBox_hor_meas_3")
        self.comboBox_hor_meas_3.addItem("")
        self.comboBox_hor_meas_3.addItem("")
        self.verticalLayout_3.addWidget(self.comboBox_hor_meas_3)
        self.line_4 = QtWidgets.QFrame(self.groupBox_2)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.verticalLayout_3.addWidget(self.line_4)
        self.lcdNumber_hor_meas_3 = QtWidgets.QLCDNumber(self.groupBox_2)
        self.lcdNumber_hor_meas_3.setObjectName("lcdNumber_hor_meas_3")
        self.verticalLayout_3.addWidget(self.lcdNumber_hor_meas_3)
        self.verticalLayout_9.addWidget(self.groupBox_2)
        self.groupBox_5 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_5.setObjectName("groupBox_5")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_8.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_8.setSpacing(6)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.comboBox_ver_mes_1 = QtWidgets.QComboBox(self.groupBox_5)
        self.comboBox_ver_mes_1.setObjectName("comboBox_ver_mes_1")
        self.comboBox_ver_mes_1.addItem("")
        self.comboBox_ver_mes_1.addItem("")
        self.verticalLayout_8.addWidget(self.comboBox_ver_mes_1)
        self.lcdNumber_ver_mes_1 = QtWidgets.QLCDNumber(self.groupBox_5)
        self.lcdNumber_ver_mes_1.setObjectName("lcdNumber_ver_mes_1")
        self.verticalLayout_8.addWidget(self.lcdNumber_ver_mes_1)
        self.line_6 = QtWidgets.QFrame(self.groupBox_5)
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.verticalLayout_8.addWidget(self.line_6)
        self.comboBox_ver_mes_2 = QtWidgets.QComboBox(self.groupBox_5)
        self.comboBox_ver_mes_2.setObjectName("comboBox_ver_mes_2")
        self.comboBox_ver_mes_2.addItem("")
        self.comboBox_ver_mes_2.addItem("")
        self.verticalLayout_8.addWidget(self.comboBox_ver_mes_2)
        self.lcdNumber_ver_mes_2 = QtWidgets.QLCDNumber(self.groupBox_5)
        self.lcdNumber_ver_mes_2.setObjectName("lcdNumber_ver_mes_2")
        self.verticalLayout_8.addWidget(self.lcdNumber_ver_mes_2)
        self.line_7 = QtWidgets.QFrame(self.groupBox_5)
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.verticalLayout_8.addWidget(self.line_7)
        self.comboBox_ver_mes_3 = QtWidgets.QComboBox(self.groupBox_5)
        self.comboBox_ver_mes_3.setObjectName("comboBox_ver_mes_3")
        self.comboBox_ver_mes_3.addItem("")
        self.comboBox_ver_mes_3.addItem("")
        self.verticalLayout_8.addWidget(self.comboBox_ver_mes_3)
        self.lcdNumber_ver_mes_3 = QtWidgets.QLCDNumber(self.groupBox_5)
        self.lcdNumber_ver_mes_3.setObjectName("lcdNumber_ver_mes_3")
        self.verticalLayout_8.addWidget(self.lcdNumber_ver_mes_3)
        self.verticalLayout_9.addWidget(self.groupBox_5)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem3)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_7.addWidget(self.scrollArea)
        self.scrollArea.raise_()
        self.pushButton_meas_dock.raise_()
        self.dockWidget_measure.setWidget(self.dockWidgetContents_4)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dockWidget_measure)
        self.dockWidget_quick_set = QtWidgets.QDockWidget(MainWindow)
        self.dockWidget_quick_set.setObjectName("dockWidget_quick_set")
        self.dockWidgetContents_2 = QtWidgets.QWidget()
        self.dockWidgetContents_2.setObjectName("dockWidgetContents_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.dockWidgetContents_2)
        self.horizontalLayout_4.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_4.setSpacing(6)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pushButton_quick_set_dock = QtWidgets.QPushButton(self.dockWidgetContents_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_quick_set_dock.sizePolicy().hasHeightForWidth())
        self.pushButton_quick_set_dock.setSizePolicy(sizePolicy)
        self.pushButton_quick_set_dock.setObjectName("pushButton_quick_set_dock")
        self.horizontalLayout_4.addWidget(self.pushButton_quick_set_dock)
        self.scrollArea_3 = QtWidgets.QScrollArea(self.dockWidgetContents_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea_3.sizePolicy().hasHeightForWidth())
        self.scrollArea_3.setSizePolicy(sizePolicy)
        self.scrollArea_3.setWidgetResizable(True)
        self.scrollArea_3.setObjectName("scrollArea_3")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 1693, 85))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.scrollAreaWidgetContents_3)
        self.horizontalLayout_6.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_6.setSpacing(6)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setSpacing(6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.spinBox_ch1_vertical = QtWidgets.QSpinBox(self.scrollAreaWidgetContents_3)
        self.spinBox_ch1_vertical.setMinimum(0)
        self.spinBox_ch1_vertical.setMaximum(511)
        self.spinBox_ch1_vertical.setProperty("value", 127)
        self.spinBox_ch1_vertical.setObjectName("spinBox_ch1_vertical")
        self.gridLayout_2.addWidget(self.spinBox_ch1_vertical, 1, 0, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_13.setObjectName("label_13")
        self.gridLayout_2.addWidget(self.label_13, 0, 0, 1, 1)
        self.pushButton_7 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_3)
        self.pushButton_7.setObjectName("pushButton_7")
        self.gridLayout_2.addWidget(self.pushButton_7, 0, 1, 1, 1)
        self.pushButton_10 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_3)
        self.pushButton_10.setObjectName("pushButton_10")
        self.gridLayout_2.addWidget(self.pushButton_10, 1, 1, 1, 1)
        self.horizontalLayout_6.addLayout(self.gridLayout_2)
        self.line_10 = QtWidgets.QFrame(self.scrollAreaWidgetContents_3)
        self.line_10.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.horizontalLayout_6.addWidget(self.line_10)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setSpacing(6)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.pushButton_15 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_3)
        self.pushButton_15.setObjectName("pushButton_15")
        self.gridLayout_5.addWidget(self.pushButton_15, 0, 1, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_15.setObjectName("label_15")
        self.gridLayout_5.addWidget(self.label_15, 0, 0, 1, 1)
        self.spinBox_5 = QtWidgets.QSpinBox(self.scrollAreaWidgetContents_3)
        self.spinBox_5.setObjectName("spinBox_5")
        self.gridLayout_5.addWidget(self.spinBox_5, 1, 0, 1, 1)
        self.pushButton_14 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_3)
        self.pushButton_14.setObjectName("pushButton_14")
        self.gridLayout_5.addWidget(self.pushButton_14, 0, 2, 1, 1)
        self.pushButton_9 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_3)
        self.pushButton_9.setObjectName("pushButton_9")
        self.gridLayout_5.addWidget(self.pushButton_9, 1, 1, 1, 1)
        self.pushButton_16 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_3)
        self.pushButton_16.setObjectName("pushButton_16")
        self.gridLayout_5.addWidget(self.pushButton_16, 1, 2, 1, 1)
        self.horizontalLayout_6.addLayout(self.gridLayout_5)
        self.line_9 = QtWidgets.QFrame(self.scrollAreaWidgetContents_3)
        self.line_9.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.horizontalLayout_6.addWidget(self.line_9)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setSpacing(6)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.spinBox_4 = QtWidgets.QSpinBox(self.scrollAreaWidgetContents_3)
        self.spinBox_4.setObjectName("spinBox_4")
        self.gridLayout_3.addWidget(self.spinBox_4, 1, 0, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_14.setObjectName("label_14")
        self.gridLayout_3.addWidget(self.label_14, 0, 0, 1, 1)
        self.pushButton_8 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_3)
        self.pushButton_8.setObjectName("pushButton_8")
        self.gridLayout_3.addWidget(self.pushButton_8, 1, 1, 1, 1)
        self.pushButton_11 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_3)
        self.pushButton_11.setObjectName("pushButton_11")
        self.gridLayout_3.addWidget(self.pushButton_11, 0, 1, 1, 1)
        self.horizontalLayout_6.addLayout(self.gridLayout_3)
        self.scrollArea_3.setWidget(self.scrollAreaWidgetContents_3)
        self.horizontalLayout_4.addWidget(self.scrollArea_3)
        self.dockWidget_quick_set.setWidget(self.dockWidgetContents_2)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(8), self.dockWidget_quick_set)
        self.dockWidget_source = QtWidgets.QDockWidget(MainWindow)
        self.dockWidget_source.setObjectName("dockWidget_source")
        self.dockWidgetContents_3 = QtWidgets.QWidget()
        self.dockWidgetContents_3.setObjectName("dockWidgetContents_3")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.dockWidgetContents_3)
        self.verticalLayout_18.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_18.setSpacing(6)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.pushButton_source_dock = QtWidgets.QPushButton(self.dockWidgetContents_3)
        self.pushButton_source_dock.setObjectName("pushButton_source_dock")
        self.verticalLayout_18.addWidget(self.pushButton_source_dock)
        self.comboBox_20 = QtWidgets.QComboBox(self.dockWidgetContents_3)
        self.comboBox_20.setObjectName("comboBox_20")
        self.comboBox_20.addItem("")
        self.comboBox_20.addItem("")
        self.comboBox_20.addItem("")
        self.comboBox_20.addItem("")
        self.comboBox_20.addItem("")
        self.comboBox_20.addItem("")
        self.verticalLayout_18.addWidget(self.comboBox_20)
        self.stackedWidget = QtWidgets.QStackedWidget(self.dockWidgetContents_3)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setObjectName("page_5")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.page_5)
        self.gridLayout_4.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_4.setSpacing(6)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.groupBox_7 = QtWidgets.QGroupBox(self.page_5)
        self.groupBox_7.setObjectName("groupBox_7")
        self.formLayout_13 = QtWidgets.QFormLayout(self.groupBox_7)
        self.formLayout_13.setContentsMargins(11, 11, 11, 11)
        self.formLayout_13.setSpacing(6)
        self.formLayout_13.setObjectName("formLayout_13")
        self.formLayout_16 = QtWidgets.QFormLayout()
        self.formLayout_16.setSpacing(6)
        self.formLayout_16.setObjectName("formLayout_16")
        self.label_27 = QtWidgets.QLabel(self.groupBox_7)
        self.label_27.setObjectName("label_27")
        self.formLayout_16.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_27)
        self.comboBox_15 = QtWidgets.QComboBox(self.groupBox_7)
        self.comboBox_15.setObjectName("comboBox_15")
        self.formLayout_16.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.comboBox_15)
        self.label_28 = QtWidgets.QLabel(self.groupBox_7)
        self.label_28.setObjectName("label_28")
        self.formLayout_16.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_28)
        self.comboBox_16 = QtWidgets.QComboBox(self.groupBox_7)
        self.comboBox_16.setObjectName("comboBox_16")
        self.comboBox_16.addItem("")
        self.comboBox_16.addItem("")
        self.comboBox_16.addItem("")
        self.comboBox_16.addItem("")
        self.comboBox_16.addItem("")
        self.formLayout_16.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.comboBox_16)
        self.label_29 = QtWidgets.QLabel(self.groupBox_7)
        self.label_29.setObjectName("label_29")
        self.formLayout_16.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_29)
        self.comboBox_17 = QtWidgets.QComboBox(self.groupBox_7)
        self.comboBox_17.setObjectName("comboBox_17")
        self.comboBox_17.addItem("")
        self.formLayout_16.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.comboBox_17)
        self.label_30 = QtWidgets.QLabel(self.groupBox_7)
        self.label_30.setObjectName("label_30")
        self.formLayout_16.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_30)
        self.comboBox_18 = QtWidgets.QComboBox(self.groupBox_7)
        self.comboBox_18.setObjectName("comboBox_18")
        self.comboBox_18.addItem("")
        self.comboBox_18.addItem("")
        self.comboBox_18.addItem("")
        self.formLayout_16.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.comboBox_18)
        self.label_31 = QtWidgets.QLabel(self.groupBox_7)
        self.label_31.setObjectName("label_31")
        self.formLayout_16.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_31)
        self.comboBox_19 = QtWidgets.QComboBox(self.groupBox_7)
        self.comboBox_19.setObjectName("comboBox_19")
        self.comboBox_19.addItem("")
        self.formLayout_16.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.comboBox_19)
        self.pushButton_17 = QtWidgets.QPushButton(self.groupBox_7)
        self.pushButton_17.setObjectName("pushButton_17")
        self.formLayout_16.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.pushButton_17)
        self.pushButton_18 = QtWidgets.QPushButton(self.groupBox_7)
        self.pushButton_18.setObjectName("pushButton_18")
        self.formLayout_16.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.pushButton_18)
        self.label_12 = QtWidgets.QLabel(self.groupBox_7)
        self.label_12.setObjectName("label_12")
        self.formLayout_16.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.label_16 = QtWidgets.QLabel(self.groupBox_7)
        self.label_16.setText("")
        self.label_16.setObjectName("label_16")
        self.formLayout_16.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.label_16)
        self.formLayout_13.setLayout(1, QtWidgets.QFormLayout.SpanningRole, self.formLayout_16)
        self.groupBox_12 = QtWidgets.QGroupBox(self.groupBox_7)
        self.groupBox_12.setObjectName("groupBox_12")
        self.formLayout_14 = QtWidgets.QFormLayout(self.groupBox_12)
        self.formLayout_14.setContentsMargins(11, 11, 11, 11)
        self.formLayout_14.setSpacing(6)
        self.formLayout_14.setObjectName("formLayout_14")
        self.formLayout_15 = QtWidgets.QFormLayout()
        self.formLayout_15.setSpacing(6)
        self.formLayout_15.setObjectName("formLayout_15")
        self.radioButton_9 = QtWidgets.QRadioButton(self.groupBox_12)
        self.radioButton_9.setChecked(True)
        self.radioButton_9.setObjectName("radioButton_9")
        self.formLayout_15.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.radioButton_9)
        self.radioButton_10 = QtWidgets.QRadioButton(self.groupBox_12)
        self.radioButton_10.setObjectName("radioButton_10")
        self.formLayout_15.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.radioButton_10)
        self.checkBox_7 = QtWidgets.QCheckBox(self.groupBox_12)
        self.checkBox_7.setChecked(True)
        self.checkBox_7.setObjectName("checkBox_7")
        self.formLayout_15.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.checkBox_7)
        self.checkBox_8 = QtWidgets.QCheckBox(self.groupBox_12)
        self.checkBox_8.setObjectName("checkBox_8")
        self.formLayout_15.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.checkBox_8)
        self.formLayout_14.setLayout(0, QtWidgets.QFormLayout.LabelRole, self.formLayout_15)
        self.formLayout_13.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.groupBox_12)
        self.groupBox_13 = QtWidgets.QGroupBox(self.groupBox_7)
        self.groupBox_13.setObjectName("groupBox_13")
        self.formLayout_17 = QtWidgets.QFormLayout(self.groupBox_13)
        self.formLayout_17.setContentsMargins(11, 11, 11, 11)
        self.formLayout_17.setSpacing(6)
        self.formLayout_17.setObjectName("formLayout_17")
        self.formLayout_18 = QtWidgets.QFormLayout()
        self.formLayout_18.setSpacing(6)
        self.formLayout_18.setObjectName("formLayout_18")
        self.radioButton_11 = QtWidgets.QRadioButton(self.groupBox_13)
        self.radioButton_11.setChecked(True)
        self.radioButton_11.setObjectName("radioButton_11")
        self.formLayout_18.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.radioButton_11)
        self.radioButton_12 = QtWidgets.QRadioButton(self.groupBox_13)
        self.radioButton_12.setObjectName("radioButton_12")
        self.formLayout_18.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.radioButton_12)
        self.checkBox_9 = QtWidgets.QCheckBox(self.groupBox_13)
        self.checkBox_9.setObjectName("checkBox_9")
        self.formLayout_18.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.checkBox_9)
        self.spinBox_3 = QtWidgets.QSpinBox(self.groupBox_13)
        self.spinBox_3.setObjectName("spinBox_3")
        self.formLayout_18.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.spinBox_3)
        self.formLayout_17.setLayout(0, QtWidgets.QFormLayout.LabelRole, self.formLayout_18)
        self.verticalLayout_15 = QtWidgets.QVBoxLayout()
        self.verticalLayout_15.setSpacing(6)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_15.addItem(spacerItem4)
        self.label_32 = QtWidgets.QLabel(self.groupBox_13)
        self.label_32.setObjectName("label_32")
        self.verticalLayout_15.addWidget(self.label_32)
        self.formLayout_17.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.verticalLayout_15)
        self.formLayout_13.setWidget(3, QtWidgets.QFormLayout.SpanningRole, self.groupBox_13)
        self.gridLayout_4.addWidget(self.groupBox_7, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_5)
        self.page_6 = QtWidgets.QWidget()
        self.page_6.setObjectName("page_6")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.page_6)
        self.gridLayout_7.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_7.setSpacing(6)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.stackedWidget.addWidget(self.page_6)
        self.verticalLayout_18.addWidget(self.stackedWidget)
        self.dockWidget_source.setWidget(self.dockWidgetContents_3)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dockWidget_source)
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionSettings = QtWidgets.QAction(MainWindow)
        self.actionSettings.setObjectName("actionSettings")
        self.actionFull_Screen = QtWidgets.QAction(MainWindow)
        self.actionFull_Screen.setObjectName("actionFull_Screen")
        self.actionNormal_Window = QtWidgets.QAction(MainWindow)
        self.actionNormal_Window.setObjectName("actionNormal_Window")
        self.actionDock_Control = QtWidgets.QAction(MainWindow)
        self.actionDock_Control.setCheckable(True)
        self.actionDock_Control.setObjectName("actionDock_Control")
        self.actionDock_Measure = QtWidgets.QAction(MainWindow)
        self.actionDock_Measure.setCheckable(True)
        self.actionDock_Measure.setObjectName("actionDock_Measure")
        self.actionDock_Quick_Set = QtWidgets.QAction(MainWindow)
        self.actionDock_Quick_Set.setCheckable(True)
        self.actionDock_Quick_Set.setObjectName("actionDock_Quick_Set")
        self.actionSerialMonitor = QtWidgets.QAction(MainWindow)
        self.actionSerialMonitor.setCheckable(True)
        self.actionSerialMonitor.setObjectName("actionSerialMonitor")
        self.actionDock_Source = QtWidgets.QAction(MainWindow)
        self.actionDock_Source.setCheckable(True)
        self.actionDock_Source.setObjectName("actionDock_Source")
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuEdit.addAction(self.actionSettings)
        self.menuView.addAction(self.actionNormal_Window)
        self.menuView.addAction(self.actionFull_Screen)
        self.menuView.addSeparator()
        self.menuView.addSeparator()
        self.menuView.addAction(self.actionDock_Control)
        self.menuView.addAction(self.actionDock_Measure)
        self.menuView.addAction(self.actionDock_Quick_Set)
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuEdit.menuAction())
        self.menuBar.addAction(self.menuView.menuAction())
        self.toolBar.addAction(self.actionExit)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionFull_Screen)
        self.toolBar.addAction(self.actionNormal_Window)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionDock_Source)
        self.toolBar.addAction(self.actionDock_Control)
        self.toolBar.addAction(self.actionDock_Measure)
        self.toolBar.addAction(self.actionDock_Quick_Set)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionSerialMonitor)
        self.label_5.setBuddy(self.comboBox_couple_mode)
        self.label_8.setBuddy(self.comboBox_4)
        self.label_9.setBuddy(self.comboBox_5)
        self.label_10.setBuddy(self.comboBox_6)
        self.label.setBuddy(self.comboBox_trigger_mode)
        self.label_2.setBuddy(self.spinBox_trigger_level)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        self.actionExit.triggered.connect(MainWindow.close)
        self.dial_gain_ch1.valueChanged['int'].connect(self.lcdNumber_gain_ch1.display)
        self.actionFull_Screen.triggered.connect(MainWindow.showFullScreen)
        self.actionNormal_Window.triggered.connect(MainWindow.showNormal)
        self.pushButton_preview_view.toggled['bool'].connect(self.graphicsView_preview.setVisible)
        self.actionSerialMonitor.toggled['bool'].connect(self.widget_serial_text.setVisible)
        self.actionDock_Quick_Set.toggled['bool'].connect(self.dockWidget_quick_set.setVisible)
        self.actionDock_Control.toggled['bool'].connect(self.dockWidget_control.setVisible)
        self.actionDock_Measure.toggled['bool'].connect(self.dockWidget_measure.setVisible)
        self.actionDock_Source.toggled['bool'].connect(self.dockWidget_source.setVisible)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.comboBox_trigger_mode, self.spinBox_trigger_level)
        MainWindow.setTabOrder(self.spinBox_trigger_level, self.graphicsView_wave)
        MainWindow.setTabOrder(self.graphicsView_wave, self.graphicsView_preview)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Oscilloscope - Nanchang University"))
        MainWindow.setToolTip(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.graphicsView_wave.setToolTip(_translate("MainWindow", "<html><head/><body><p>Waveform Display</p></body></html>"))
        self.pushButton_13.setText(_translate("MainWindow", "Send"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit"))
        self.menuView.setTitle(_translate("MainWindow", "View"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.dockWidget_control.setToolTip(_translate("MainWindow", "<html><head/><body><p>Control Dock Window</p></body></html>"))
        self.dockWidget_control.setWindowTitle(_translate("MainWindow", "Control"))
        self.pushButton_ctrl_dock.setText(_translate("MainWindow", "Dock"))
        self.groupBox_3.setToolTip(_translate("MainWindow", "<html><head/><body><p>CH1 Settings</p></body></html>"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Channel 1"))
        self.label_6.setText(_translate("MainWindow", "Vertical"))
        self.label_5.setText(_translate("MainWindow", "Couple Mode"))
        self.comboBox_couple_mode.setItemText(0, _translate("MainWindow", "DC"))
        self.comboBox_couple_mode.setItemText(1, _translate("MainWindow", "AC"))
        self.label_8.setText(_translate("MainWindow", "Probe"))
        self.comboBox_4.setItemText(0, _translate("MainWindow", "X1"))
        self.comboBox_4.setItemText(1, _translate("MainWindow", "X10"))
        self.label_9.setText(_translate("MainWindow", "TextLabel"))
        self.dial_ofst_ch1.setToolTip(_translate("MainWindow", "<html><head/><body><p>Offset Position</p></body></html>"))
        self.pushButton_ofst_rst_ch1.setToolTip(_translate("MainWindow", "<html><head/><body><p>Offset Position Reset</p></body></html>"))
        self.pushButton_ofst_rst_ch1.setText(_translate("MainWindow", "Offset Reset"))
        self.groupBox_4.setToolTip(_translate("MainWindow", "<html><head/><body><p>Time Base Settings</p></body></html>"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Time Base"))
        self.label_7.setText(_translate("MainWindow", "Horizontal"))
        self.label_10.setText(_translate("MainWindow", "Dimension Mode"))
        self.comboBox_6.setItemText(0, _translate("MainWindow", "X-T"))
        self.comboBox_6.setItemText(1, _translate("MainWindow", "Roll"))
        self.comboBox_6.setItemText(2, _translate("MainWindow", "X-Y"))
        self.pushButton_preview_view.setText(_translate("MainWindow", "Preview"))
        self.pushButton_freq_domain.setText(_translate("MainWindow", "Freq Domain"))
        self.dial_ofst_time.setToolTip(_translate("MainWindow", "<html><head/><body><p>Offset Position</p></body></html>"))
        self.pushButton_ofst_rst_time.setToolTip(_translate("MainWindow", "<html><head/><body><p>Offset Position Reset</p></body></html>"))
        self.pushButton_ofst_rst_time.setText(_translate("MainWindow", "Offset Reset"))
        self.groupBox.setTitle(_translate("MainWindow", "Trigger"))
        self.label.setText(_translate("MainWindow", "Mode"))
        self.comboBox_trigger_mode.setItemText(0, _translate("MainWindow", "Normal"))
        self.comboBox_trigger_mode.setItemText(1, _translate("MainWindow", "Auto"))
        self.comboBox_trigger_mode.setItemText(2, _translate("MainWindow", "Single"))
        self.label_2.setText(_translate("MainWindow", "Level"))
        self.dial_time_ofst_2.setToolTip(_translate("MainWindow", "<html><head/><body><p>Offset Position</p></body></html>"))
        self.toolButton_2.setText(_translate("MainWindow", "½"))
        self.pushButton.setText(_translate("MainWindow", "Set Zero"))
        self.pushButton_2.setText(_translate("MainWindow", "Auto"))
        self.groupBox_6.setTitle(_translate("MainWindow", "Display"))
        self.label_3.setText(_translate("MainWindow", "Brightness"))
        self.label_4.setText(_translate("MainWindow", "Drawing Width"))
        self.label_11.setText(_translate("MainWindow", "Drawing Mode"))
        self.pushButton_5.setText(_translate("MainWindow", "Reset"))
        self.pushButton_3.setText(_translate("MainWindow", "Save"))
        self.dockWidget_measure.setToolTip(_translate("MainWindow", "<html><head/><body><p>Measure Dock Window</p></body></html>"))
        self.dockWidget_measure.setWindowTitle(_translate("MainWindow", "Measure"))
        self.pushButton_meas_dock.setText(_translate("MainWindow", "Dock"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Horizontal"))
        self.comboBox_hor_meas_1.setItemText(0, _translate("MainWindow", "Period"))
        self.comboBox_hor_meas_1.setItemText(1, _translate("MainWindow", "Frequency"))
        self.comboBox_hor_meas_2.setItemText(0, _translate("MainWindow", "Period"))
        self.comboBox_hor_meas_2.setItemText(1, _translate("MainWindow", "Frequency"))
        self.comboBox_hor_meas_3.setItemText(0, _translate("MainWindow", "Period"))
        self.comboBox_hor_meas_3.setItemText(1, _translate("MainWindow", "Frequency"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Vertical"))
        self.comboBox_ver_mes_1.setItemText(0, _translate("MainWindow", "Vp-p"))
        self.comboBox_ver_mes_1.setItemText(1, _translate("MainWindow", "Vavg"))
        self.comboBox_ver_mes_2.setItemText(0, _translate("MainWindow", "Vp-p"))
        self.comboBox_ver_mes_2.setItemText(1, _translate("MainWindow", "Vavg"))
        self.comboBox_ver_mes_3.setItemText(0, _translate("MainWindow", "Vp-p"))
        self.comboBox_ver_mes_3.setItemText(1, _translate("MainWindow", "Vavg"))
        self.dockWidget_quick_set.setToolTip(_translate("MainWindow", "<html><head/><body><p>Quick Set Dock Window</p></body></html>"))
        self.dockWidget_quick_set.setWindowTitle(_translate("MainWindow", "Quick Set"))
        self.pushButton_quick_set_dock.setText(_translate("MainWindow", "Dock"))
        self.label_13.setText(_translate("MainWindow", "CH1 Vertical"))
        self.pushButton_7.setText(_translate("MainWindow", "mV/Div"))
        self.pushButton_10.setText(_translate("MainWindow", "V/Div"))
        self.pushButton_15.setText(_translate("MainWindow", "ns/Div"))
        self.label_15.setText(_translate("MainWindow", "Horizontal"))
        self.pushButton_14.setText(_translate("MainWindow", "us/Div"))
        self.pushButton_9.setText(_translate("MainWindow", "ms/Div"))
        self.pushButton_16.setText(_translate("MainWindow", "s/Div"))
        self.label_14.setText(_translate("MainWindow", "Trigger"))
        self.pushButton_8.setText(_translate("MainWindow", "V"))
        self.pushButton_11.setText(_translate("MainWindow", "mV"))
        self.dockWidget_source.setWindowTitle(_translate("MainWindow", "Source"))
        self.pushButton_source_dock.setText(_translate("MainWindow", "Dock"))
        self.comboBox_20.setItemText(0, _translate("MainWindow", "Serial"))
        self.comboBox_20.setItemText(1, _translate("MainWindow", "TCP/UDP"))
        self.comboBox_20.setItemText(2, _translate("MainWindow", "SPI"))
        self.comboBox_20.setItemText(3, _translate("MainWindow", "IIC"))
        self.comboBox_20.setItemText(4, _translate("MainWindow", "Bluetooth"))
        self.comboBox_20.setItemText(5, _translate("MainWindow", "Subprocess Pipe"))
        self.groupBox_7.setTitle(_translate("MainWindow", "Serial Config"))
        self.label_27.setText(_translate("MainWindow", "Port"))
        self.label_28.setText(_translate("MainWindow", "Buadrate"))
        self.comboBox_16.setItemText(0, _translate("MainWindow", "1200"))
        self.comboBox_16.setItemText(1, _translate("MainWindow", "2400"))
        self.comboBox_16.setItemText(2, _translate("MainWindow", "4800"))
        self.comboBox_16.setItemText(3, _translate("MainWindow", "9600"))
        self.comboBox_16.setItemText(4, _translate("MainWindow", "115200"))
        self.label_29.setText(_translate("MainWindow", "Data Bit"))
        self.comboBox_17.setItemText(0, _translate("MainWindow", "8"))
        self.label_30.setText(_translate("MainWindow", "Parity"))
        self.comboBox_18.setItemText(0, _translate("MainWindow", "None"))
        self.comboBox_18.setItemText(1, _translate("MainWindow", "Even"))
        self.comboBox_18.setItemText(2, _translate("MainWindow", "Odd"))
        self.label_31.setText(_translate("MainWindow", "Stop Bit"))
        self.comboBox_19.setItemText(0, _translate("MainWindow", "1"))
        self.pushButton_17.setText(_translate("MainWindow", "Open Port"))
        self.pushButton_18.setText(_translate("MainWindow", "Close Port"))
        self.label_12.setText(_translate("MainWindow", "Description"))
        self.groupBox_12.setTitle(_translate("MainWindow", "Receive Config"))
        self.radioButton_9.setText(_translate("MainWindow", "ASCII"))
        self.radioButton_10.setText(_translate("MainWindow", "Hex"))
        self.checkBox_7.setText(_translate("MainWindow", "Auto Scroll"))
        self.checkBox_8.setText(_translate("MainWindow", "Show Time"))
        self.groupBox_13.setTitle(_translate("MainWindow", "Send Config"))
        self.radioButton_11.setText(_translate("MainWindow", "ASCII"))
        self.radioButton_12.setText(_translate("MainWindow", "Hex"))
        self.checkBox_9.setText(_translate("MainWindow", "Repeat"))
        self.label_32.setText(_translate("MainWindow", "ms"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionExit.setShortcut(_translate("MainWindow", "Ctrl+Q"))
        self.actionSettings.setText(_translate("MainWindow", "Settings"))
        self.actionFull_Screen.setText(_translate("MainWindow", "Full Screen"))
        self.actionFull_Screen.setToolTip(_translate("MainWindow", "Full Screen"))
        self.actionNormal_Window.setText(_translate("MainWindow", "Normal Window"))
        self.actionDock_Control.setText(_translate("MainWindow", "Dock Control"))
        self.actionDock_Control.setToolTip(_translate("MainWindow", "Dock Control"))
        self.actionDock_Measure.setText(_translate("MainWindow", "Dock Measure"))
        self.actionDock_Quick_Set.setText(_translate("MainWindow", "Dock Quick Set"))
        self.actionSerialMonitor.setText(_translate("MainWindow", "Serial Monitor"))
        self.actionDock_Source.setText(_translate("MainWindow", "Dock Source"))

from pyqtgraph import PlotWidget
